# Generated by Django 5.1.3 on 2024-11-18 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='court_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('level_class', models.CharField(choices=[('beginner', '初級'), ('intermediate', '中級'), ('advanced', '上級')], max_length=20)),
                ('category', models.CharField(choices=[('mix', '男女MIX'), ('mens', 'メンズ'), ('ladies', 'レディース'), ('kids', 'キッズ')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.facility')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.event'),
        ),
    ]
