# Generated by Django 5.1.3 on 2024-11-18 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_reservation_court_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_facilities', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'facility')},
            },
        ),
    ]
