# Generated by Django 5.1.4 on 2024-12-07 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_scrapedevent_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedevent',
            name='converted_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_event', to='users.event'),
        ),
    ]
