# Generated by Django 5.1.4 on 2024-12-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_scrapedevent_converted_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedevent',
            name='event_url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='scrapedevent',
            unique_together={('event_name', 'event_date', 'start_time', 'location')},
        ),
    ]
