# Generated by Django 5.1.4 on 2024-12-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_event_options_alter_event_unique_together'),
    ]

    operations = [
    ]
