# Generated by Django 5.1.4 on 2024-12-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20241207_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedevent',
            name='converted_event',
        ),
    ]
