# Generated by Django 5.1.4 on 2024-12-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_scrapedevent_converted_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedevent',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_source', to='users.event'),
        ),
    ]
