# Generated by Django 5.1.4 on 2024-12-07 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_scrapedevent_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedevent',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='scraped_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='users.scrapedevent'),
        ),
    ]
