# Generated by Django 5.1.4 on 2024-12-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_scrapedevent_event_event_scraped_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scraped_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='users.scrapedevent'),
        ),
    ]
