# Generated by Django 5.1.4 on 2024-12-07 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_event_scraped_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='scraped_source',
        ),
        migrations.AddField(
            model_name='scrapedevent',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_source', to='users.event'),
        ),
    ]
